[phases.setup]
nixPkgs = ["nodejs_20", "bun"]

[phases.install]
cmds = ["bun i --no-save"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "exec caddy run --config /assets/Caddyfile --adapter caddyfile 2>&1"